In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import pickle

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import plot_confusion_matrix, recall_score, accuracy_score, precision_score, f1_score
from sklearn.pipeline import Pipeline

In [2]:
loaded_model = pickle.load(open('./best_model_logreg_T', 'rb'))

In [80]:
df = pd.read_csv('../data/full.csv', index_col=0)
df.columns

Index(['matchId', 'blue_team_kills', 'red_team_kills', 'blue_team_visionScore',
       'red_team_visionScore', 'blue_team_assists', 'red_team_assists',
       'blue_team_cs', 'red_team_cs', 'blue_team_level', 'red_team_level',
       'blue_dragons_slained', 'red_dragons_slained',
       'blue_rift_heralds_slained', 'red_rifts_heralds_slained',
       'blue_AIR_DRAGON', 'red_AIR_DRAGON', 'blue_EARTH_DRAGON',
       'red_EARTH_DRAGON', 'blue_FIRE_DRAGON', 'red_FIRE_DRAGON',
       'blue_HEXTECH_DRAGON', 'red_HEXTECH_DRAGON', 'blue_WATER_DRAGON',
       'red_WATER_DRAGON', 'blue_inhibitors_destroyed',
       'red_inhibitors_destroyed', 'blue_towers_destroyed',
       'red_towers_destroyed', 'win'],
      dtype='object')

In [50]:
df_check = df.drop(columns='matchId')
X = df_check.drop(columns='win')
y = df_check.win

In [76]:
df.iloc[0]

matchId                      NA1_4307254820
blue_team_kills                        14.0
red_team_kills                         10.0
blue_team_visionScore                  32.0
red_team_visionScore                   28.0
blue_team_assists                      11.0
red_team_assists                        9.0
blue_team_cs                            416
red_team_cs                             453
blue_team_level                          46
red_team_level                           46
blue_dragons_slained                      2
red_dragons_slained                       0
blue_rift_heralds_slained                 0
red_rifts_heralds_slained                 1
blue_AIR_DRAGON                           0
red_AIR_DRAGON                            0
blue_EARTH_DRAGON                         0
red_EARTH_DRAGON                          0
blue_FIRE_DRAGON                          1
red_FIRE_DRAGON                           0
blue_HEXTECH_DRAGON                       0
red_HEXTECH_DRAGON                        0
blue_WATER_DRAGON                         1
red_WATER_DRAGON                          0
blue_inhibitors_destroyed                 0
red_inhibitors_destroyed                  0
blue_towers_destroyed                     1
red_towers_destroyed                      2
win                                    Blue
Name: 0, dtype: object

In [99]:
pd.DataFrame(X.iloc[0]).T

,blue_team_kills,red_team_kills,blue_team_visionScore,red_team_visionScore,blue_team_assists,red_team_assists,blue_team_cs,red_team_cs,blue_team_level,red_team_level,...,blue_FIRE_DRAGON,red_FIRE_DRAGON,blue_HEXTECH_DRAGON,red_HEXTECH_DRAGON,blue_WATER_DRAGON,red_WATER_DRAGON,blue_inhibitors_destroyed,red_inhibitors_destroyed,blue_towers_destroyed,red_towers_destroyed
0,14.0,10.0,32.0,28.0,11.0,9.0,416.0,453.0,46.0,46.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0

In [97]:
loaded_model.predict_proba(X)

array([[0.77164868, 0.22835132],
       [0.04166794, 0.95833206],
       [0.5365396 , 0.4634604 ],
       ...,
       [0.7116769 , 0.2883231 ],
       [0.35827302, 0.64172698],
       [0.83333664, 0.16666336]])

In [103]:
loaded_model.predict(X)

array([0, 1, 0, ..., 0, 1, 0], dtype=int64)

In [53]:
df.win

0        Blue
1         Red
2        Blue
3         Red
4        Blue
         ...
12259    Blue
12260     Red
12261    Blue
12262     Red
12263     Red
Name: win, Length: 23074, dtype: object

In [55]:
Blue_proba = []
Red_proba = []
for game in loaded_model.predict_proba(X):
    Blue_proba.append(game[0])
    Red_proba.append(game[1])

In [62]:
data = {'Pred_prob_Blue':Blue_proba,'Pred_prob_Red':Red_proba,'Pred':loaded_model.predict(X),'Actual':df.win}

In [63]:
probability_model_df = pd.DataFrame(data,columns=['Pred_prob_Blue','Pred_prob_Red','Pred_prob_Red','Pred','Actual'])

In [64]:
probability_model_df

       Pred_prob_Blue  Pred_prob_Red  Pred_prob_Red  Pred Actual
0            0.771649       0.228351       0.228351     0   Blue
1            0.041668       0.958332       0.958332     1    Red
2            0.536540       0.463460       0.463460     0   Blue
3            0.062752       0.937248       0.937248     1    Red
4            0.648759       0.351241       0.351241     0   Blue
...               ...            ...            ...   ...    ...
12259        0.653577       0.346423       0.346423     0   Blue
12260        0.054295       0.945705       0.945705     1    Red
12261        0.711677       0.288323       0.288323     0   Blue
12262        0.358273       0.641727       0.641727     1    Red
12263        0.833337       0.166663       0.166663     0    Red

[23074 rows x 5 columns]

In [65]:
probability_model_df['Pred'] = probability_model_df.Pred.replace(0, 'Blue').replace(1, 'Red')

In [66]:
probability_model_df

       Pred_prob_Blue  Pred_prob_Red  Pred_prob_Red  Pred Actual
0            0.771649       0.228351       0.228351  Blue   Blue
1            0.041668       0.958332       0.958332   Red    Red
2            0.536540       0.463460       0.463460  Blue   Blue
3            0.062752       0.937248       0.937248   Red    Red
4            0.648759       0.351241       0.351241  Blue   Blue
...               ...            ...            ...   ...    ...
12259        0.653577       0.346423       0.346423  Blue   Blue
12260        0.054295       0.945705       0.945705   Red    Red
12261        0.711677       0.288323       0.288323  Blue   Blue
12262        0.358273       0.641727       0.641727   Red    Red
12263        0.833337       0.166663       0.166663  Blue    Red

[23074 rows x 5 columns]

In [68]:
probability_model_df['Correct'] =  (probability_model_df.Pred == probability_model_df.Actual)
probability_model_df

       Pred_prob_Blue  Pred_prob_Red  Pred_prob_Red  Pred Actual  Correct
0            0.771649       0.228351       0.228351  Blue   Blue     True
1            0.041668       0.958332       0.958332   Red    Red     True
2            0.536540       0.463460       0.463460  Blue   Blue     True
3            0.062752       0.937248       0.937248   Red    Red     True
4            0.648759       0.351241       0.351241  Blue   Blue     True
...               ...            ...            ...   ...    ...      ...
12259        0.653577       0.346423       0.346423  Blue   Blue     True
12260        0.054295       0.945705       0.945705   Red    Red     True
12261        0.711677       0.288323       0.288323  Blue   Blue     True
12262        0.358273       0.641727       0.641727   Red    Red     True
12263        0.833337       0.166663       0.166663  Blue    Red    False

[23074 rows x 6 columns]

In [71]:
probability_model_df.Correct.value_counts(normalize=True)

True     0.774811
False    0.225189
Name: Correct, dtype: float64

In [180]:
def win_proba():
    team = str(input('What team are you?: '))
    
    blue_team_kills = int(input('blue_team_kills: '))
    red_team_kills = int(input('red_team_kills: '))
    blue_team_visionScore = int(input('blue_team_visionScore: '))
    red_team_visionScore = int(input('red_team_visionScore: '))
    blue_team_assists = int(input('blue_team_assists: '))
    red_team_assists = int(input('red_team_assists: '))
    blue_team_cs = int(input('blue_team_cs: '))
    red_team_cs = int(input('red_team_cs: '))
    blue_team_level = int(input('blue_team_level: '))
    red_team_level = int(input('red_team_level: '))
    blue_dragons_slained = int(input('blue_dragons_slained: '))
    red_dragons_slained = int(input('red_dragons_slained: '))
    blue_rift_heralds_slained = int(input('blue_rift_heralds_slained: '))
    red_rifts_heralds_slained = int(input('red_rifts_heralds_slained: '))
    blue_AIR_DRAGON = int(input('blue_AIR_DRAGON: '))
    red_AIR_DRAGON = int(input('red_AIR_DRAGON: '))
    blue_EARTH_DRAGON = int(input('blue_EARTH_DRAGON: '))
    red_EARTH_DRAGON = int(input('red_EARTH_DRAGON: '))
    blue_FIRE_DRAGON = int(input('blue_FIRE_DRAGON: '))
    red_FIRE_DRAGON = int(input('red_FIRE_DRAGON: '))
    blue_HEXTECH_DRAGON = int(input('blue_HEXTECH_DRAGON: '))
    red_HEXTECH_DRAGON = int(input('red_HEXTECH_DRAGON: '))
    blue_WATER_DRAGON = int(input('blue_WATER_DRAGON: '))
    red_WATER_DRAGON = int(input('red_WATER_DRAGON: '))
    blue_inhibitors_destroyed = int(input('blue_inhibitors_destroyed: '))
    red_inhibitors_destroyed = int(input('red_inhibitors_destroyed: '))
    blue_towers_destroyed = int(input('blue_towers_destroyed: '))
    red_towers_destroyed = int(input('red_towers_destroyed: '))
    
    total_inputs = [blue_team_kills,red_team_kills,blue_team_visionScore,red_team_visionScore,blue_team_assists,red_team_assists,blue_team_cs,red_team_cs,blue_team_level,red_team_level,blue_dragons_slained,red_dragons_slained,blue_rift_heralds_slained,red_rifts_heralds_slained,blue_AIR_DRAGON,red_AIR_DRAGON,blue_EARTH_DRAGON,red_EARTH_DRAGON,blue_FIRE_DRAGON,red_FIRE_DRAGON,blue_HEXTECH_DRAGON,red_HEXTECH_DRAGON,blue_WATER_DRAGON,red_WATER_DRAGON,blue_inhibitors_destroyed,red_inhibitors_destroyed,blue_towers_destroyed,red_towers_destroyed]
    
    data = {'blue_team_kills':[blue_team_kills],'red_team_kills':[red_team_kills],'blue_team_visionScore':[blue_team_visionScore],
            'red_team_visionScore':[red_team_visionScore],'blue_team_assists':[blue_team_assists],
            'red_team_assists':[red_team_assists],'blue_team_cs':[blue_team_cs],'red_team_cs':[red_team_cs],
            'blue_team_level':[blue_team_level],'red_team_level':[red_team_level],'blue_dragons_slained':[blue_dragons_slained],
            'red_dragons_slained':[red_dragons_slained],'blue_rift_heralds_slained':[blue_rift_heralds_slained],
            'red_rifts_heralds_slained':[red_rifts_heralds_slained],'blue_AIR_DRAGON':[blue_AIR_DRAGON],
            'red_AIR_DRAGON':[red_AIR_DRAGON],'blue_EARTH_DRAGON':[blue_EARTH_DRAGON],'red_EARTH_DRAGON':[red_EARTH_DRAGON],
            'blue_FIRE_DRAGON':[blue_FIRE_DRAGON],'red_FIRE_DRAGON':[red_FIRE_DRAGON],'blue_HEXTECH_DRAGON':[blue_HEXTECH_DRAGON],
            'red_HEXTECH_DRAGON':[red_HEXTECH_DRAGON],'blue_WATER_DRAGON':[blue_WATER_DRAGON],'red_WATER_DRAGON':[red_WATER_DRAGON],
            'blue_inhibitors_destroyed':[blue_inhibitors_destroyed],'red_inhibitors_destroyed':[red_inhibitors_destroyed],
            'blue_towers_destroyed':[blue_towers_destroyed],'red_towers_destroyed':[red_towers_destroyed]}

    probability_model_df = pd.DataFrame(data,columns=['blue_team_kills','red_team_kills','blue_team_visionScore','red_team_visionScore','blue_team_assists','red_team_assists','blue_team_cs','red_team_cs','blue_team_level','red_team_level','blue_dragons_slained','red_dragons_slained','blue_rift_heralds_slained','red_rifts_heralds_slained','blue_AIR_DRAGON','red_AIR_DRAGON','blue_EARTH_DRAGON','red_EARTH_DRAGON','blue_FIRE_DRAGON','red_FIRE_DRAGON','blue_HEXTECH_DRAGON','red_HEXTECH_DRAGON','blue_WATER_DRAGON','red_WATER_DRAGON','blue_inhibitors_destroyed','red_inhibitors_destroyed','blue_towers_destroyed','red_towers_destroyed'])
    
    team_predictions = loaded_model.predict_proba(probability_model_df)
 
    if team == 'Blue': 
        return (f'You have a {round(team_predictions[0][0]*100,1)}% chance of winning') 
    elif team == 'Red':
        return (f'You have a {round(team_predictions[0][1]*100,1)}% chance of winning')

In [183]:
win_proba()

What team are you?: Blue
blue_team_kills: 10
red_team_kills: 10
blue_team_visionScore: 10
red_team_visionScore: 10
blue_team_assists: 10
red_team_assists: 10
blue_team_cs: 10
red_team_cs: 10
blue_team_level: 10
red_team_level: 10
blue_dragons_slained: 0
red_dragons_slained: 0
blue_rift_heralds_slained: 0
red_rifts_heralds_slained: 0
blue_AIR_DRAGON:

ValueError: invalid literal for int() with base 10: ''

In [125]:
data = {'blue_team_kills':[10],'red_team_kills':[10],'blue_team_visionScore':[10],
            'red_team_visionScore':[10],'blue_team_assists':[10],
            'red_team_assists':[10],'blue_team_cs':[100],'red_team_cs':[100],
            'blue_team_level':[10],'red_team_level':[10],'blue_dragons_slained':[0],
            'red_dragons_slained':[0],'blue_rift_heralds_slained':[0],
            'red_rifts_heralds_slained':[0],'blue_AIR_DRAGON':[0],
            'red_AIR_DRAGON':[0],'blue_EARTH_DRAGON':[0],'red_EARTH_DRAGON':[0],
            'blue_FIRE_DRAGON':[0],'red_FIRE_DRAGON':[0],'blue_HEXTECH_DRAGON':[0],
            'red_HEXTECH_DRAGON':[0],'blue_WATER_DRAGON':[0],'red_WATER_DRAGON':[0],
            'blue_inhibitors_destroyed':[0],'red_inhibitors_destroyed':[0],
            'blue_towers_destroyed':[0],'red_towers_destroyed':[0]}

probability_model_df = pd.DataFrame(data,columns=['blue_team_kills','red_team_kills','blue_team_visionScore','red_team_visionScore','blue_team_assists','red_team_assists','blue_team_cs','red_team_cs','blue_team_level','red_team_level','blue_dragons_slained','red_dragons_slained','blue_rift_heralds_slained','red_rifts_heralds_slained','blue_AIR_DRAGON','red_AIR_DRAGON','blue_EARTH_DRAGON','red_EARTH_DRAGON','blue_FIRE_DRAGON','red_FIRE_DRAGON','blue_HEXTECH_DRAGON','red_HEXTECH_DRAGON','blue_WATER_DRAGON','red_WATER_DRAGON','blue_inhibitors_destroyed','red_inhibitors_destroyed','blue_towers_destroyed','red_towers_destroyed'])
probability_model_df

,blue_team_kills,red_team_kills,blue_team_visionScore,red_team_visionScore,blue_team_assists,red_team_assists,blue_team_cs,red_team_cs,blue_team_level,red_team_level,...,blue_FIRE_DRAGON,red_FIRE_DRAGON,blue_HEXTECH_DRAGON,red_HEXTECH_DRAGON,blue_WATER_DRAGON,red_WATER_DRAGON,blue_inhibitors_destroyed,red_inhibitors_destroyed,blue_towers_destroyed,red_towers_destroyed
0,10,10,10,10,10,10,100,100,10,10,...,0,0,0,0,0,0,0,0,0,0

In [171]:
loaded_model.predict_proba(pd.DataFrame(X.iloc[0]).T)[0]

array([0.77164868, 0.22835132])

In [140]:
win_proba()

blue_team_kills: 10
red_team_kills: 10
blue_team_visionScore: 10
red_team_visionScore: 10
blue_team_assists: 10
red_team_assists: 10
blue_team_cs: 10
red_team_cs: 10
blue_team_level: 10
red_team_level: 10
blue_dragons_slained: 10
red_dragons_slained: 10
blue_rift_heralds_slained: 1
red_rifts_heralds_slained: 10
blue_AIR_DRAGON: 0
red_AIR_DRAGON: 0
blue_EARTH_DRAGON: 0
red_EARTH_DRAGON: 0
blue_FIRE_DRAGON: 0
red_FIRE_DRAGON: 0
blue_HEXTECH_DRAGON: 0
red_HEXTECH_DRAGON: 0
blue_WATER_DRAGON: 0
red_WATER_DRAGON: 0
blue_inhibitors_destroyed: 0
red_inhibitors_destroyed: 0
blue_towers_destroyed: 0
red_towers_destroyed: 0

array([[0.33811344, 0.66188656]])

In [ ]:
00